const products = [
    { id: 1, name: "Lego F1 Car",             price: 49.99, age: "3-6",brand: "Lego" , src:"https://www.lego.com/cdn/cs/set/assets/blt9b6d585ea7fbd636/10353_Box5_v39_en-gb.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 2, name: "Lego Creator",            price: 19.99, age: "0-3",brand: "Lego",  src:"https://www.lego.com/cdn/cs/set/assets/blt16bd4a6872327a68/31145_alt6.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 3, name: "Lego Starry Night",       price: 24.99, age: "9+", brand: "Lego" , src:"https://www.lego.com/cdn/cs/set/assets/blt19c726cb9dc878d7/21333_alt8.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 4, name: "Lego Radio",              price: 89.99, age: "9+", brand: "Lego" , src:"https://www.lego.com/cdn/cs/set/assets/blt4979b6ff335c13ed/10334_Box5_v39.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 5, name: "Lego Imperial Star",      price: 59.99, age: "9+", brand: "Lego" , src:"https://www.lego.com/cdn/cs/set/assets/blt080aba34587b00b2/75394_Box5_v39.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 6, name: "Lego Snow White Cottage", price: 129.99,age: "6-9",brand: "Lego" , src:"https://www.lego.com/cdn/cs/set/assets/blt254a95020cd1fecc/43242_alt8.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5" },
    { id: 7, name: "Nerf Elite 2.0",          price: 19.99 ,age: "6-9",brand: "Nerf" , src:"nerf-product-1.png" },
    { id: 8, name: "Nerf N Pinpoint",         price: 29.99, age: "3-6",brand: "Nerf" , src:"nerf-product-2.png" },
    { id: 9, name: "Nerf ULTRA",              price: 19.99 ,age: "9+", brand: "Nerf" , src:"nerf-product-3.png" },
    { id: 10, name: "Nerf Gel Fire",          price: 29.99 ,age: "9+", brand: "Nerf" , src:"nerf-product-4(2).png" },
    { id: 11, name: "Nerf Infinite",          price: 19.99 ,age: "6-9",brand: "Nerf" , src:"nerf-product-5.png" },
    { id: 12, name: "Nerf Pro Sender",        price: 24.99 ,age: "3-6",brand: "Nerf" , src:"nerf-product-6.png" },
    { id: 13, name: "Holiday Barbie",         price: 19.99 ,age: "0-3",brand: "Barbie",src:"barbie-product-1.png" },
    { id: 14, name: "Barbie Dream Closet",    price: 39.99 ,age: "3-6",brand: "Barbie",src:"barbie-product-2.png" },
    { id: 15, name: "Barbie Brooklyn",        price: 9.99 , age: "0-3",brand: "Barbie",src:"barbie-product-3(2).png" },
    { id: 16, name: "Barbie Pizza Chef",      price: 14.99 ,age: "3-6",brand: "Barbie",src:"barbie-product-4.png" },
    { id: 17, name: "My First Barbie",        price: 9.99 , age: "0-3",brand: "Barbie",src:"barbie-product-5.png" },
    { id: 18, name: "Barbie Getaway House",   price: 49.99 ,age: "0-3",brand: "Barbie",src:"barbie-product-6.png" },
    { id: 19, name: "Hotwheels Corvette",     price: 9.99 ,age: "6-9",brand: "Hotwheel",src:"hotwheel-product-1.png" },
    { id: 20, name: "Hotwheels Aston Martin", price: 4.99 ,age: "0-3",brand: "Hotwheel",src:"hotwheel-product-2.png" },
    { id: 21, name: "Hotwheels Fire Truck",   price: 14.99 ,age: "6-9",brand: "Hotwheel",src:"hotwheel-product-3.png" },
    { id: 22, name: "Hotwheels Track Set",    price: 24.99 ,age: "9+",brand: "Hotwheel",src:"hotwheel-product-4.png" },
    { id: 23, name: "Hotwheels Cadillac",     price: 9.99 ,age: "3-6",brand: "Hotwheel",src:"hotwheel-product-5.png" },
    { id: 24, name: "Hotwheels Monster Truck",price: 21.99 ,age: "6-9",brand: "Hotwheel",src:"hotwheel-product-6.png" },
    { id: 25, name: "Enzo Lunch Box",         price: 7.99 ,age: "0-3",brand: "School",src:"school-product-1.png" },
    { id: 26, name: "Homeatic Water Bottle",  price: 49.99 ,age: "9+",brand: "School",src:"school-product-2.png" },
    { id: 27, name: "Pony Backpack",          price: 34.99 ,age: "6-9",brand: "School",src:"school-product-3.png" },
    { id: 28, name: "Fortnite Backpack",      price: 34.99 ,age: "9+",brand: "School",src:"school-product-4.png" },
    { id: 29, name: "Water Color",            price: 4.99 ,age: "3-6",brand: "School",src:"school-product-5.png" },
    { id: 30, name: "Paint Brushes",          price: 6.99 ,age: "3-6",brand: "School",src:"school-product-6.png" },
    
];
